### ISSUE TITLE
Duplicating reports

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#32]
**When duplicating an existing report definition, only the filter definition is copied but no the selected columns for output:**
<img width="1217" alt="Bildschirmfoto 2021-03-22 um 09 21 18" src="https://user-images.githubusercontent.com/74606126/111960460-11c77300-8af0-11eb-997e-94d81de49a54.png">

**Suggested improvement: Rename the existing report title by adding "copy" as a suffix to clearly mark and identify the copied entry:**
<img width="687" alt="Bildschirmfoto 2021-03-22 um 09 23 09" src="https://user-images.githubusercontent.com/74606126/111960628-40dde480-8af0-11eb-9bb3-307f36455c47.png">

**Comment by frederikbugglin** [comment]
deleting selected reports does not work, even though success message appears after completion of the task

**Comment by saemideluxe** [comment]
Fixed (the soft delete was also configured to be enabled for all objects instead only for persons)

**Comment by frederikbugglin** [comment]
error 500 when opening the copied report

<img width="619" alt="Bildschirmfoto 2021-03-30 um 11 35 42" src="https://user-images.githubusercontent.com/74606126/112967968-1ae9bd00-914c-11eb-8909-373188e8d6a5.png">

**Comment by saemideluxe** [comment]
Okay, fixed. The problem was happening when opening any report-edit screen, due to a refactoring.

**Comment by saemideluxe** [comment]
@frederikbugglin Can you confirm this works as expected and close the issue?

**Comment by frederikbugglin** [comment]
when duplicating an existing report, the error message is not displayed any longer. however, the report is still not created and not displayed (tested on the pws staging instance)

**Comment by saemideluxe** [comment]
Okay, should be working on pws staging now.

**Comment by frederikbugglin** [comment]
### Test

**Test Environment** UM DEV, DEMO, PWS STAGING, PWS LIVE
**Menu name** Reports/List overview
**Action taken** Selected an existing report from the list and duplicated it with data table action bar
**Expected result** A new report is created (indicated by _Copy_ suffix) and the existing report definition is copied 
**Test result(s)** successful: UM DEV, DEMO, PWS STAGING // failed on PWS LIVE

#### **Further action steps**
- [ ] Bug fix needs to be deployed to PWS LIVE

**Comment by saemideluxe** [comment]
Okay, I am aware of this. I will wait until you approve that #87 is working on the PWS staging and then do the update in one go.
